openapi: 3.0.3
info:
  title: Amazing users service
  description: Amazing users service
  version: 1.0.0
servers:
  - url: 'http://localhost:9002'
    description: Development server
paths:

  /users/{pseudo}:
    parameters:
      - name: pseudo
        in: path
        description: Pseudo of the user
        schema:
          type: string
          example: SebStreb
    post:
      summary: Create user
      requestBody:
        description: User to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        400:
          description: Non matching parameters
        409:
          description: Already exists
        200:
          description: User created
    get:
      summary: Read user
      responses:
        404:
          description: Not found
        200:
          description: User found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/user'
    put:
      summary: Update user
      requestBody:
        description: New values of the user
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/user'
      responses:
        400:
          description: Non matching parameters
        404:
          description: Not found
        200:
          description: User updated
    delete:
      summary: Delete user
      responses:
        404:
          description: Not found
        200:
          description: User deleted

components:
  schemas:
    user:
      type: object
      properties:
        pseudo:
          type: string
        firstname:
          type: string
        lastname:
          type: string
      example:
        pseudo: SebStreb
        firstname: Sébastien
        lastname: Strebelle
